version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    networks:
      - app-network
    depends_on:
      - smart-contract
    environment:
      - VITE_SMART_CONTRACT_ADDRESS=${SMART_CONTRACT_ADDRESS}
      - VITE_RPC_URL=http://smart-contract:8545

  smart-contract:
    build:
      context: ./smart_contract
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./smart_contract:/usr/src/app/smart_contract
      - /usr/src/app/smart_contract/node_modules
    networks:
      - app-network
    environment:
      - REPORT_GAS=true

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  client:
  smart_contract:
